// Generated by CoffeeScript 1.6.2
(function() {
  $("document").ready(function() {
    var allroutes, listBooks, router, routes, showAuthorInfo;

    showAuthorInfo = function() {
      return console.log("showAuthorInfo");
    };
    listBooks = function() {};
    allroutes = function() {};
    routes = {
      "/game1": function() {
        return Popup.open('game1', 845, 642);
      },
      "/list": function() {
        return Popup.closeCurrent();
      }
    };
    router = Router(routes);
    router.configure({
      on: allroutes
    });
    return router.init();
  });

  window.close = function() {
    return Popup.closeCurrent();
  };

}).call(this);
